version: "3"
services:
  nacos:
    image: nacos/nacos-server:2.0.3
    container_name: nacos1
     # 将容器加入指定网络
    networks:
      mynetwork:
        ipv4_address: 172.31.12.2   #设置ip地址
    restart: always
    environment:
      - MODE=standalone
      - JVM_XMS=512m
      - JVM_MMS=320m
      - JVM_XMN=256m
    ports:
      - 8848:8848

#设置网络环境
networks:
  #引用外部预先定义好的网段
  mynetwork:
    driver: "bridge"
    ipam: ## 配置网络
     config:
       - subnet: 172.31.12.0/24


# http://127.0.0.1:8848/nacos/#/login