# grafana admin/admin
version: "3.7"
services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: "node-exporter0"
    ports:
      - "9100:9100"
    restart: always
  prometheus:
    image: prom/prometheus:latest
    container_name: "prometheus0"
    restart: always
    ports:
      - "9191:9090"
    volumes:
      - /Users/zhangtingting/docker/prometheus/prometheus.yml:/vehicle/prometheus/prometheus.yml
      - /Users/zhangtingting/docker/prometheus/prometheus_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: "grafana"
    ports:
      - "3001:3000"
    restart: always
    volumes:
      - /Users/zhangtingting/docker/prometheus/grafana_data:/var/lib/grafana
