#博客地址
#https://blog.csdn.net/yanyan42/article/details/100936895
#https://www.cnblogs.com/hxsen/p/13456665.html

version: "2.4"

services:
  php:
    image: php:7.1-fpm
    restart: always
    container_name: php
    ports:
      - 9001:9000
    volumes:
      - /Users/zhangtingting/project:/project
      - /Users/zhangtingting/docker/php:/usr/local/etc/php
      - /usr/local/lib/php/pecl/20160303:/usr/local/lib/php/pecl/20160303
    networks:
      mynetwork:
        ipv4_address: 172.27.0.23   #设置ip地址

#设置网络环境
networks:
  #引用外部预先定义好的网段
  mynetwork:
    ipam: ## 配置网络
      config:
      - subnet: 172.27.0.0/16 ## ip地址网络 这里宿主机一般会是该网段的172.27.0.1,所以不要设置自网段为1
