

# redis.yaml configuration
redis:
  addr: '127.0.0.1:6379'
  password: ''
  db: 0
  maxRetries: 3
  PoolSize: 3000
  poolTimeout: 240s
  minIdleConns: 200
  dialTimeout: 10s
  readTimeout: 500ms
  writeTimeout: 500ms
  enableTrace: true


trace:
  serviceName: "gin"
  traceAgent: "jaeger" #jaeger

  jaeger:
    samplingServerURL: "1.0"
    localAgentHostPort: "127.0.0.1:6831"
    collectorEndpoint: "http://localhost:14268/api/traces"
    collectorUser: ""
    collectorPassword: ""


