#博客地址
#https://blog.csdn.net/pingweicheng/article/details/105473283
#https://www.cnblogs.com/idea360/p/12391416.html

#compose命令注释详解 https://www.jianshu.com/p/90bf0e231e5a
#redis常见问题 https://www.cnblogs.com/apanly/p/12430499.html
# 指定compose文件的版本
version: '3.7'
# 定义所有的service信息,services下面的第一级别的key即是一个service的名称
services:
  master-1:
    # 指定 docker 镜像, 可以是远程仓库镜像、本地镜像
    image: redis:5.0.5
    # 指定容器的名称 (等同于 docker run --name 的作用)
    container_name: redis-master-1
    # 定义容器重启策略 no 禁止自动重启容器(默认)|always 无论如何容器都会重启|on-failure 报错时, 容器重新启动
    restart: on-failure
    ports:
      - 6061:6061
      - 16061:16061
    # 将容器加入指定网络
    networks:
      mynetwork:
        ipv4_address: 172.22.0.101   #设置ip地址
    stdin_open: true
    tty: true
    # 定义容器和宿主机的卷映射关系
    volumes:
      - /Users/zhangtingting/docker/redis-cluster/node1/data:/data
      - /Users/zhangtingting/docker/redis-cluster/node1:/usr/local/etc/redis
      - /Users/zhangtingting/docker/redis-cluster/node1/data:/usr/local/var/db/redis
    # 覆盖容器启动后默认执行的命令, 支持 shell 格式和 [] 格式
    command:
      /usr/local/bin/redis-server /usr/local/etc/redis/redis.conf
    environment:
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai

  slave-1:
    image: redis:5.0.5
    container_name: redis-slave-1
    restart: on-failure
    ports:
      - 6062:6062
      - 16062:16062
    networks:
      mynetwork:
        ipv4_address: 172.22.0.102   #设置ip地址
    stdin_open: true
    tty: true
    volumes:
      - /Users/zhangtingting/docker/redis-cluster/node2/data:/data
      - /Users/zhangtingting/docker/redis-cluster/node2:/usr/local/etc/redis
      - /Users/zhangtingting/docker/redis-cluster/node2/data:/usr/local/var/db/redis
    command:
      /usr/local/bin/redis-server /usr/local/etc/redis/redis.conf
    environment:
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai

  master-2:
    image: redis:5.0.5
    container_name: redis-master-2
    restart: on-failure
    ports:
      - 6063:6063
      - 16063:16063
    networks:
      mynetwork:
        ipv4_address: 172.22.0.103   #设置ip地址
    stdin_open: true
    tty: true
    volumes:
      - /Users/zhangtingting/docker/redis-cluster/node3/data:/data
      - /Users/zhangtingting/docker/redis-cluster/node3:/usr/local/etc/redis
      - /Users/zhangtingting/docker/redis-cluster/node3/data:/usr/local/var/db/redis
    command:
      /usr/local/bin/redis-server /usr/local/etc/redis/redis.conf
    environment:
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai

  slave-2:
    image: redis:5.0.5
    container_name: redis-slave-2
    restart: on-failure
    ports:
      - 6064:6064
      - 16064:16064
    networks:
      mynetwork:
        ipv4_address: 172.22.0.104   #设置ip地址
    stdin_open: true
    tty: true
    volumes:
      - /Users/zhangtingting/docker/redis-cluster/node4/data:/data
      - /Users/zhangtingting/docker/redis-cluster/node4:/usr/local/etc/redis
      - /Users/zhangtingting/docker/redis-cluster/node4/data:/usr/local/var/db/redis
    command:
      /usr/local/bin/redis-server /usr/local/etc/redis/redis.conf
    environment:
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai

  master-3:
    image: redis:5.0.5
    container_name: redis-master-3
    restart: on-failure
    ports:
      - 6065:6065
      - 16065:16065
    networks:
      mynetwork:
        ipv4_address: 172.22.0.105   #设置ip地址
    stdin_open: true
    tty: true
    volumes:
      - /Users/zhangtingting/docker/redis-cluster/node5/data:/data
      - /Users/zhangtingting/docker/redis-cluster/node5:/usr/local/etc/redis
      - /Users/zhangtingting/docker/redis-cluster/node5/data:/usr/local/var/db/redis
    command:
      /usr/local/bin/redis-server /usr/local/etc/redis/redis.conf
    environment:
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai

  slave-3:
    image: redis:5.0.5
    container_name: redis-slave-3
    restart: on-failure
    ports:
      - 6066:6066
      - 16066:16066
    networks:
      mynetwork:
        ipv4_address: 172.22.0.106   #设置ip地址
    stdin_open: true
    tty: true
    volumes:
      - /Users/zhangtingting/docker/redis-cluster/node6/data:/data
      - /Users/zhangtingting/docker/redis-cluster/node6:/usr/local/etc/redis
      - /Users/zhangtingting/docker/redis-cluster/node6/data:/usr/local/var/db/redis
    command:
      /usr/local/bin/redis-server /usr/local/etc/redis/redis.conf
    environment:
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai


#设置网络环境
networks:
  #引用外部预先定义好的网段
  mynetwork:
    ipam: ## 配置网络
     config:
       - subnet: 172.22.0.0/16 ## ip地址网络 这里宿主机一般会是该网段的172.22.0.1,所以不要设置自网段为1

#       宿主机(ip 端口)	容器(ip 端口)
#       10.99.8.9:6061	172.22.0.101:6061
#       10.99.8.9:6062	172.22.0.102:6062
#       10.99.8.9:6063	172.22.0.103:6063
#       10.99.8.9:6064	172.22.0.104:6064
#       10.99.8.9:6065	172.22.0.105:6065
#       10.99.8.9:6066	172.22.0.106:6066
